
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/okd/scos-content
    digest: sha256:65309b6ab011b271111902a74df02c6090e401e86de99635b82027ffc02a1bb6
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/okd/scos-content
    digest: sha256:f94028f396f197106266aff0d143f70bc363850b5d5853ec74863951d4d81888
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/okd/scos-content
    digest: sha256:6d4056bf69022cd09ecf845fb46c1743ad4aaa394b935285d1c5af5dac681f10

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/okd/scos-content@sha256:f94028f396f197106266aff0d143f70bc363850b5d5853ec74863951d4d81888
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/okd/scos-content@sha256:65309b6ab011b271111902a74df02c6090e401e86de99635b82027ffc02a1bb6
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
