
images:
  - name: multus-cni-microshift
    newName: quay.io/okd/scos-content
    digest: sha256:ad6ad5731956b2cbfc7d2728cbc4425a66e2a8c1330ce669f8f6c4eba0d794c4
  - name: containernetworking-plugins-microshift
    newName: quay.io/okd/scos-content
    digest: sha256:879ba685165e141272dbd5f9d8de8887d49fc701790a8dd14f5d9d3fc67192f2
